# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lobbyranking der Bundesl√§nder
url: "https://lobbyranking.de/"

# Build settings
markdown: kramdown
collections:
  states:
    output: true
    permalink: /laender/:path/

exclude:
  - node_modules
  - .git
